project:
  type: website
  resources:
    - models/yolov8n.onnx

website:
  title: "![](img/MUCDAI_Logo.png){.second-logo}"
  navbar:
    background: "#ffd1d4"
    foreground: "#1a1814"
    logo: "img/HM_Logo.png"
    logo-alt: "Hochschule München"
    search: true
    right:
      - text: "GitHub"
        href: "https://github.com/billyS02/vcde"
        icon: github

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    grid:
      body-width: 1100px
      sidebar-width: 0px
      margin-width: 280px