project:
  type: website
  resources:
    - models/yolov8n.onnx

website:
  title: "Search""
  sidebar:
    title: false
    search: true


format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3