project:
  type: website
  resources:
    - models/yolov8n.onnx

website:
  title: "Echtzeit-Objekterkennung mit YOLO"
  sidebar:
    search: true
    contents:
      - index.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3